/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ptit.dental;

import org.junit.jupiter.api.Test;

import com.ptit.dental.utils.Database;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(Database.getInstance(), "app should have a database connection");
    }
}
