///*
// * This source file was generated by the Gradle 'init' task
// */
//package com.ptit.dental;
//
//
//import com.ptit.dental.view.CleanLoginView;
//
//import javax.swing.UIManager;
//
//public class App {
//   public static void main(String[] args) {
//        // Initialize database and services in a separate thread to avoid blocking UI
//        Thread dbInitThread = new Thread(() -> {
//            try {
//                com.ptit.dental.utils.Database db = com.ptit.dental.utils.Database.getInstance();
//                java.sql.Connection conn = db.getConnection();
//                com.ptit.dental.model.dao.StaffDAO staffDAO = new com.ptit.dental.model.dao.StaffDAO(conn);
//
//                com.ptit.dental.utils.Injector.register(com.ptit.dental.model.dao.StaffDAO.class, staffDAO);
//                com.ptit.dental.utils.Injector.register(com.ptit.dental.model.service.AuthService.class,
//                    new com.ptit.dental.model.service.AuthService(staffDAO));
//
//                System.out.println("Database initialized successfully");
//            } catch (Exception e) {
//                System.err.println("Database initialization failed: " + e.getMessage());
//                System.err.println("Application will continue without database connectivity");
//            }
//        });
//
//        // Start database initialization in background
//        dbInitThread.start();
//
//        // Initialize UI immediately
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
//            } catch (Exception e) {
//                System.err.println("Could not set Nimbus look and feel: " + e.getMessage());
//            }
//            // Sử dụng CleanLoginFrame không có lỗi encoding
//            new CleanLoginView().setVisible(true);
//        });
//   }
//}

package com.ptit.dental;


import com.ptit.dental.controller.LoginController;
import com.ptit.dental.model.dao.StaffDAO;
import com.ptit.dental.model.service.AuthService;
import com.ptit.dental.utils.Database;
import com.ptit.dental.utils.Injector;
import com.ptit.dental.view.LoginView;

import javax.swing.*;

public class App {
    public static void main(String[] args) {

        // === 1. Khởi tạo database và service trên thread riêng ===
        Thread dbInitThread = new Thread(() -> {
            try {
                Database db = Database.getInstance();
                java.sql.Connection conn = db.getConnection();
                StaffDAO staffDAO = new StaffDAO(conn);
                AuthService authService = new AuthService(staffDAO);

                Injector.register(StaffDAO.class, staffDAO);
                Injector.register(AuthService.class, authService);

                System.out.println("✅ Database initialized successfully");
            } catch (Exception e) {
                System.err.println("⚠️ Database initialization failed: " + e.getMessage());
            }
        });
        dbInitThread.start();

        // === 2. Khởi tạo UI ===
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            } catch (Exception e) {
                System.err.println("Could not set Nimbus Look and Feel: " + e.getMessage());
            }

            // Sử dụng Controller đúng mô hình MVC
            LoginView loginView = new LoginView();
            LoginController controller = new LoginController(loginView);
            controller.show();
        });
    }
}
