/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ptit.dental;

import com.ptit.dental.controller.*;
import com.ptit.dental.model.dao.StaffDAO;
import com.ptit.dental.model.entity.Staff;
import com.ptit.dental.model.service.AuthService;
import com.ptit.dental.utils.Database;
import com.ptit.dental.utils.Injector;
import com.ptit.dental.view.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



public class App {
   public static void main(String[] args) throws SQLException {

        Database db = Database.getInstance();

        Connection conn = db.getConnection();

        StaffDAO staffDAO = new StaffDAO(conn);

        Injector.register(StaffDAO.class, staffDAO);
        Injector.register(AuthService.class, new AuthService(staffDAO));

        java.awt.EventQueue.invokeLater(() -> {
            //new LoginController(new LoginView()).show();
//            new MedicalRecordController(new  MedicalRecordView()).show();
           new InvoiceController(new InvoiceView()).show();
//           new SearchingInvoiceController(new SearchingInvoice()).show();
//            new MedicineListController(new MedicineListView()).show();
//
        });
   }
}